spring:
  application:
   name: antifraud
  mongodb:
     uri: ${MONGO_URL}

  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      group-id: ${apps.kafka.groupId}

app:
  highAmountValue: ${HIGH_AMOUNT_VALUE}
  midAmountValue: ${MID_AMOUNT_VALUE}
  startHourTime: ${START_HOUR_TIME}
  endHourTime: ${END_HOUR_TIME}
  acksConfig: ${ACKS_CONFIG}
  collection: ${MONGO_COLLECTION}
  kafka:
    consumerId: ${GROUP_ID_ANTIFRAUD}
    server: ${KAFKA_SERVER}
    trustDeserializer: ${TRUST_PACKAGES_ANTIFRAUD}
    mappingNewAntiFraud: ${NEW_ANTIFRAUD}
    newPaymentTopic: ${TOPIC_PAYMENT_REQUESTED:payment.requested}
    maxAttempt: ${KAFKA_MAX_RETRY}
    retryInterval: ${KAFKA_INTERVAL_RETRY}
    producer:
      type-mapping: ${PRODUCER_TYPE_MAPPING}
      topic: ${TOPIC_ANTI_FRAUD}
server:
  port: 8090



